# To run: conda env create -f environment.yml
# freely change the pytorch, cudatoolkit version, as you preferred.
# only works with tqdm==4.40.0 for now.
name: multi-mono-sf
channels:
    - pytorch
    - conda-forge
dependencies:
    - python=3.8
    - pytorch==1.8.1
    - torchvision
    - torchaudio
    - cudatoolkit=10.1
    - opencv
    - colorama
    - scikit-image
    - cupy
    - pytz
    - tqdm==4.40.0
    - tensorboard